// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBktfPPotMr8itvrH3-z4ab4nJLPB8Xeo',
    appId: '1:965324284587:web:1786ba0ce40dccc09b0dee',
    messagingSenderId: '965324284587',
    projectId: 'check24-betapp',
    authDomain: 'check24-betapp.firebaseapp.com',
    storageBucket: 'check24-betapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxJCLXGOmKl7xsAA4kDM10dROds0IUjnc',
    appId: '1:965324284587:android:35b24606951d1bcd9b0dee',
    messagingSenderId: '965324284587',
    projectId: 'check24-betapp',
    storageBucket: 'check24-betapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHr9OUNFKuRbktt2IMlblGJbouBsaOxd8',
    appId: '1:965324284587:ios:3b204a4413a2a98e9b0dee',
    messagingSenderId: '965324284587',
    projectId: 'check24-betapp',
    storageBucket: 'check24-betapp.appspot.com',
    iosBundleId: 'com.jakoblandbrecht.betapp',
  );
}
